version: "3.8"

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: nest

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
